# 
# Copyright 2025 EDT&Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

"""Update Course table

Revision ID: 2bf0f0114584
Revises: f9f6d58893f0
Create Date: 2025-04-29 18:34:24.371308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bf0f0114584'
down_revision: Union[str, None] = 'f9f6d58893f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('alias_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.add_column('courses', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('courses', sa.Column('conversation_access_token', sa.String(), nullable=True))

    # Remove "agent_id" and "alias_id" from "courses" table if they exist
    op.execute("""
        ALTER TABLE courses
        DROP COLUMN IF EXISTS agent_id,
        DROP COLUMN IF EXISTS alias_id;
    """)

    op.execute("""
        INSERT INTO agents (id, code, name, description, agent_id, alias_id, created_at, updated_at) 
        VALUES('3f8db27d-e45b-4e67-9158-1e6845226a5c'::uuid, 'external_chatbot', 'External chatbot', 'Used for external chatbots', '7CEIEMDN1N', 'BBU5LCCD41', '2025-04-29 17:51:44.296', '2025-04-29 17:51:44.296');
        
        INSERT INTO agents (id, code, name, description, agent_id, alias_id, created_at, updated_at) 
        VALUES('7529c6ad-cfb0-4b8b-b5dc-8981fc2a65e5'::uuid, 'internal_chatbot_without_kb', 'Internal chatbot without kb', 'Used for internal chatbots without knowledge base', 'LWVGRI8D3F', 'FYWFVKK68V', '2025-04-29 17:54:06.345', '2025-04-29 17:54:06.345');
        
        INSERT INTO agents (id, code, name, description, agent_id, alias_id, created_at, updated_at) 
        VALUES('eea19dbe-ef23-4a82-ac76-026d4ff1de8b'::uuid, 'internal_chatbot_with_kb', 'Internal chatbot with kb', 'Used for internal chatbots with knowledge base', '8H6GPQCITL', 'JT3D12C5AN', '2025-04-29 17:54:41.996', '2025-04-29 17:54:41.996');
        
        INSERT INTO services (id, name, code, description, isknowledgebase) VALUES('9a4fdda1-da00-4ca5-a136-aa4568e98c0a'::uuid, 'Knowledge Bases', 'knowledge_base_manager', 'Knowledge base Manager', false);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'conversation_access_token')
    op.drop_column('courses', 'settings')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
