# 
# Copyright 2025 EDT&Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

"""create third party integrations table

Revision ID: 5456c539496c
Revises: 01842328c25a
Create Date: 2025-05-20 13:10:34.469851

"""
from typing import Sequence, Union
from uuid import uuid4
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5456c539496c'
down_revision: Union[str, None] = '01842328c25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SERVER_DEFAULT_NOW = sa.text('now()')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_integrations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('service_name', sa.String(), nullable=False),
        sa.Column('service_value', postgresql.JSONB(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=SERVER_DEFAULT_NOW, nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=SERVER_DEFAULT_NOW, onupdate=SERVER_DEFAULT_NOW, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('service_name', name='uq_service')
    )
    op.create_index(op.f('ix_third_party_integrations_id'), 'third_party_integrations', ['id'], unique=False)

    # Define default service values
    default_service_values = {
        "sentry": {
            "dsn": "",
            "environment": "production"
        },
        "google": {
            "client_id": ""
        }
    }

    # Insert services globally (once each)
    connection = op.get_bind()
    for service_name, service_value in default_service_values.items():
        connection.execute(
            sa.text("""
                INSERT INTO third_party_integrations (id, service_name, service_value)
                VALUES (:id, :service_name, :service_value)
            """),
            {
                "id": uuid4(),
                "service_name": service_name,
                "service_value": json.dumps(service_value)
            }
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_party_integrations_id'), table_name='third_party_integrations')
    op.drop_table('third_party_integrations')
    # ### end Alembic commands ###