# © [2025] EDT&Partners. Licensed under CC BY 4.0.

"""Update chatbots table with lti config

Revision ID: 6c9fc5098093
Revises: 5e01daebf9b3
Create Date: 2025-09-23 14:32:54.204713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c9fc5098093'
down_revision: Union[str, None] = '5e01daebf9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('lti_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'lti_config')
    # ### end Alembic commands ###
