# 
# Copyright 2025 EDT&Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

"""Add S3 Bucket configuration to Admin dashboard

Revision ID: 7bc0fa4eebdb
Revises: 5456c539496c
Create Date: 2025-05-27 13:29:41.738622

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bc0fa4eebdb'
down_revision: Union[str, None] = '5456c539496c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO third_party_integrations(id, service_name, service_value) 
        VALUES ('2d884de4-ce9c-4176-9377-bf310b5c725e', 's3', '{"bucket_name":"", "region":""}');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM third_party_integrations WHERE service_name = 's3';
    """)
    # ### end Alembic commands ###
