# © [2025] EDT&Partners. Licensed under CC BY 4.0.

"""Add S3 Bucket configuration to Admin dashboard

Revision ID: 7bc0fa4eebdb
Revises: 5456c539496c
Create Date: 2025-05-27 13:29:41.738622

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bc0fa4eebdb'
down_revision: Union[str, None] = '5456c539496c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO third_party_integrations(id, service_name, service_value) 
        VALUES ('2d884de4-ce9c-4176-9377-bf310b5c725e', 's3', '{"bucket_name":"", "region":""}');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM third_party_integrations WHERE service_name = 's3';
    """)
    # ### end Alembic commands ###
