# 
# Copyright 2025 EDT&Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

"""initial migration

Revision ID: 9b03a58a4561
Revises: 
Create Date: 2025-01-15 15:03:57.133360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9b03a58a4561'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('suffix')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isknowledgebase', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('max_input_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_modalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_modalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inference', sa.Boolean(), nullable=True),
    sa.Column('supports_knowledge_base', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('logo_s3_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('group_models',
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'model_id')
    )
    op.create_table('group_services',
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'service_id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('cognito_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='userrole', create_type=False), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('comparison_configs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('threshold', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_configs_id'), 'comparison_configs', ['id'], unique=False)
    op.create_table('comparison_documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('s3_uri', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('comparison_engine_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_documents_id'), 'comparison_documents', ['id'], unique=False)
    op.create_table('comparison_engines',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_engines_id'), 'comparison_engines', ['id'], unique=False)
    op.create_table('comparison_rules',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_rules_id'), 'comparison_rules', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('knowledge_base_id', sa.String(), nullable=True),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.Column('ingestion_job_id', sa.String(), nullable=True),
    sa.Column('execution_arn', sa.String(), nullable=True),
    sa.Column('sample_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_status', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('requests',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_id'), 'rubrics', ['id'], unique=False)
    op.create_table('analytics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('request_token_count', sa.Integer(), nullable=True),
    sa.Column('response_token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.create_table('course_student',
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('rubric_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('student_surname', sa.String(), nullable=False),
    sa.Column('exam_description', sa.String(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('criteria_evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_table('invites',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('s3_uri', sa.String(), nullable=False),
    sa.Column('transcription_s3_uri', sa.String(), nullable=True),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('performance_indicators',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('rubric_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_indicators_id'), 'performance_indicators', ['id'], unique=False)
    op.create_table('podcasts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('dialog', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_s3_uri', sa.String(), nullable=True),
    sa.Column('image_s3_uri', sa.String(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_course_id'), 'questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_request_id'), 'questions', ['request_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('s3_uri', sa.String(), nullable=False),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    
    
    op.execute("""
        INSERT INTO regions (id, name, suffix, s3_bucket)
        VALUES
        ('83b21e5e-2a64-41d4-918b-e21434b74102', 'us-east-1', 'us', 'lecture-models-us-east-1'),
        ('bbbf5e14-e6b4-47ac-a9cd-026a49e91c10', 'eu-central-1', 'eu', 'lecture-models-eu-central-1')
    """)
    
    op.execute("""
        INSERT INTO ai_models (name, provider, identifier, is_default, max_input_tokens, max_output_tokens, input_modalities, output_modalities, inference, supports_knowledge_base, category, description, region_id)
        VALUES
            ('Nova Pro', 'Amazon', 'amazon.nova-pro-v1:0', true, 4096, 2048, '["Text", "Image", "Video"]', '["Text"]', true, true, 'high-end', 'Best for document evaluation, complex reasoning, and high-accuracy tasks', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Nova Lite', 'Amazon', 'amazon.nova-lite-v1:0', false, 4096, 2048, '["Text", "Image", "Video"]', '["Text"]', true, true, 'mid-tier', 'Suitable for general chat, basic analysis, and moderate workloads', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Nova Micro', 'Amazon', 'amazon.nova-micro-v1:0', false, 4096, 2048, '["Text"]', '["Text"]', true, true, 'mid-tier', 'Suitable for general chat, basic analysis, and moderate workloads', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Nova Canvas', 'Amazon', 'amazon.nova-canvas-v1:0', false, 4096, 2048, '["Text"]', '["Image"]', false, false, 'specialized', 'Used for image generation', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Nova Reel', 'Amazon', 'amazon.nova-reel-v1:0', false, 4096, 2048, '["Text"]', '["Video"]', false, false, 'specialized', 'Used for video generation', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Claude 3.5 Sonnet', 'Anthropic', 'anthropic.claude-3-5-sonnet-20240620-v1:0', true, 200000, 4096, '["Text", "Image"]', '["Text"]', true, true, 'high-end', 'Best for document evaluation, complex reasoning, and high-accuracy tasks', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Claude 3 Sonnet', 'Anthropic', 'anthropic.claude-3-sonnet-20240229-v1:0', false, 200000, 4096, '["Text", "Image"]', '["Text"]', true, true, 'high-end', 'Best for document evaluation, complex reasoning, and high-accuracy tasks', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Claude 2.0', 'Anthropic', 'anthropic.claude-v2', false, 100000, 4096, '["Text"]', '["Text"]', false, true, 'mid-tier', 'Suitable for general chat, basic analysis, and moderate workloads', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Claude Instant', 'Anthropic', 'anthropic.claude-instant-v1', false, 100000, 4096, '["Text"]', '["Text"]', false, true, 'mid-tier', 'Suitable for general chat, basic analysis, and moderate workloads', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Llama 3.2 1B Instruct', 'Meta', 'meta.llama3-2-1b-instruct-v1:0', false, 128000, 4096, '["Text"]', '["Text"]', true, true, 'lightweight', 'Budget-friendly models for general chat and lightweight tasks', '83b21e5e-2a64-41d4-918b-e21434b74102'),
            ('Llama 3.2 3B Instruct', 'Meta', 'meta.llama3-2-3b-instruct-v1:0', true, 128000, 4096, '["Text"]', '["Text"]', true, true, 'lightweight', 'Budget-friendly models for general chat and lightweight tasks', '83b21e5e-2a64-41d4-918b-e21434b74102')
    """)
    
    op.execute("""
        INSERT INTO services (name, code, description, isknowledgebase)
        VALUES
        ('Knowledge Base Chat', 'knowledge_base_chat_service', 'Chat with an agent to get answers to your questions', true),
        ('AI Rich Text Editor', 'ai_rich_text_editor_service', 'Summarize, expand and rephrase text with AI powered features', false),
        ('Evaluations', 'evaluations_service', 'Manage exams evaluated with rubrics', false),
        ('Knowledge Base Questions Generator', 'knowledge_base_questions_generator', 'Generate exam questions based on the knowledge base material', true),
        ('Podcast Generator', 'podcast_generator', 'Generate a podcast from a pdf file', false),
        ('Comparison Engine', 'comparison_engine', 'Compare two documents and get the gaps.', false),
        ('In-doc Translation', 'translation_service', 'Make exact copies of your docs in another language', false),
        ('Content Chat', 'content_query_service', 'Query content from uploaded documents or web pages', false),
        ('Transcriber', 'transcription_service', 'Transcribe audio and video content into text', false),
        ('Exam Questions Generator', 'questions_generator_service', 'Generate exam questions based on a course content or material', false)
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_questions_request_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_course_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_table('podcasts')
    op.drop_index(op.f('ix_performance_indicators_id'), table_name='performance_indicators')
    op.drop_table('performance_indicators')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('course_student')
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_rubrics_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_comparison_rules_id'), table_name='comparison_rules')
    op.drop_table('comparison_rules')
    op.drop_index(op.f('ix_comparison_engines_id'), table_name='comparison_engines')
    op.drop_table('comparison_engines')
    op.drop_index(op.f('ix_comparison_documents_id'), table_name='comparison_documents')
    op.drop_table('comparison_documents')
    op.drop_index(op.f('ix_comparison_configs_id'), table_name='comparison_configs')
    op.drop_table('comparison_configs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('group_services')
    op.drop_table('group_models')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
