# 
# Copyright 2025 EDT&Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

"""Add columns to analytics table

Revision ID: f9f6d58893f0
Revises: c994dbd0dd54
Create Date: 2025-04-15 14:22:37.777419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f9f6d58893f0'
down_revision: Union[str, None] = 'c994dbd0dd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('response_type', sa.String(), nullable=True))
    op.add_column('analytics', sa.Column('error', sa.String(), nullable=True))
    op.add_column('analytics', sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analytics', sa.Column('status', sa.String(), nullable=True))
    op.add_column('analytics', sa.Column('processing_time', sa.Float(), nullable=True))
    op.add_column('analytics', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('analytics', sa.Column('reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'estimated_cost')
    op.drop_column('analytics', 'processing_time')
    op.drop_column('analytics', 'status')
    op.drop_column('analytics', 'model_parameters')
    op.drop_column('analytics', 'error')
    op.drop_column('analytics', 'response_type')
    op.drop_column('analytics', 'reference')
    # ### end Alembic commands ###
